import Image from "../../../../assets/blog.png";

const blogPostData = [
    {
      id: 1,
      title: "DAOs and Their Impact",
      content: "## What are DAOs? A DAO is a collectively-owned, blockchain-governed organization working towards a common goal...",
      date: "July 31, 2023",
      image: Image,
      tags: ["AI", "StartUp"],
    },
    {
      id: 2,
      title: "Understanding Blockchain Technology",
      content: "## Blockchain Basics. Blockchain is a decentralized ledger technology that enables secure transactions...",
      date: "August 1, 2023",
      image: Image,
      tags: ["Blockchain", "Tech"],
    },
    {
      id: 3,
      title: "The Future of AI in Business",
      content: "## AI Applications. Artificial Intelligence is revolutionizing industries by improving efficiency and innovation...",
      date: "August 2, 2023",
      image: Image,
      tags: ["AI", "Business"],
    },
    {
      id: 4,
      title: "How Startups Are Changing the Economy",
      content: "## The Rise of Startups. Startups are driving innovation and creating jobs in various sectors...",
      date: "August 3, 2023",
      image: Image,
      tags: ["StartUp", "Economy"],
    },
    {
      id: 5,
      title: "Emerging Trends in FinTech",
      content: "## FinTech Innovations. Financial Technology is transforming how we manage money and banking...",
      date: "August 4, 2023",
      image: Image,
      tags: ["FinTech", "Finance"],
    },
    {
      id: 6,
      title: "Large Language Models Explained",
      content: "## Understanding LLMs. Large Language Models are advanced AI systems that can understand and generate human-like text...",
      date: "August 5, 2023",
      image: Image,
      tags: ["AI", "Tech"],
    },
    {
      id: 7,
      title: "New Features in Web Development",
      content: "## What's New? The web development landscape is continuously evolving with new frameworks and tools...",
      date: "August 6, 2023",
      image: Image,
      tags: ["Web Development", "Tech"],
    },
    {
      id: 8,
      title: "The Importance of Cybersecurity",
      content: "## Protecting Your Data. As technology advances, so do the threats to our digital security...",
      date: "August 7, 2023",
      image: Image,
      tags: ["Cybersecurity", "Tech"],
    },
    {
      id: 9,
      title: "Digital Marketing Strategies",
      content: "## Marketing in the Digital Age. Explore effective strategies for engaging customers online...",
      date: "August 8, 2023",
      image: Image,
      tags: ["Marketing", "Business"],
    },
    {
      id: 10,
      title: "Sustainable Practices in Tech",
      content: "## Going Green. Learn how technology companies are adopting sustainable practices...",
      date: "August 9, 2023",
      image: Image,
      tags: ["Sustainability", "Tech"],
    },
    {
      id: 11,
      title: "Exploring Quantum Computing",
      content: "## What is Quantum Computing? Delve into the principles of quantum mechanics that power this new frontier...",
      date: "August 10, 2023",
      image: Image,
      tags: ["Quantum Computing", "Tech"],
    },
    {
      id: 12,
      title: "The Evolution of Social Media",
      content: "## From Facebook to TikTok. Explore how social media platforms have transformed our interactions...",
      date: "August 11, 2023",
      image: Image,
      tags: ["Social Media", "Culture"],
    },
    {
      id: 13,
      title: "Virtual Reality in Education",
      content: "## Immersive Learning. How VR is changing the way we approach education and training...",
      date: "August 12, 2023",
      image: Image,
      tags: ["VR", "Education"],
    },
    {
      id: 14,
      title: "AI in Healthcare",
      content: "## Transforming Patient Care. Discover how AI is enhancing diagnosis and treatment in healthcare...",
      date: "August 13, 2023",
      image: Image,
      tags: ["AI", "Healthcare"],
    },
    {
      id: 15,
      title: "Mobile App Development Trends",
      content: "## What's Next? Stay ahead of the curve with the latest trends in mobile app development...",
      date: "August 14, 2023",
      image: Image,
      tags: ["Mobile", "Tech"],
    },
    {
      id: 16,
      title: "The Role of Big Data",
      content: "## Insights and Analysis. Understanding how big data is shaping decision-making in businesses...",
      date: "August 15, 2023",
      image: Image,
      tags: ["Big Data", "Business"],
    },
    {
      id: 17,
      title: "Cryptocurrency Market Overview",
      content: "## Navigating the Crypto Space. An overview of the current trends and future of cryptocurrencies...",
      date: "August 16, 2023",
      image: Image,
      tags: ["Cryptocurrency", "Finance"],
    },
    {
      id: 18,
      title: "The Impact of 5G Technology",
      content: "## Faster Connections. Explore how 5G is revolutionizing communication and connectivity...",
      date: "August 17, 2023",
      image: Image,
      tags: ["5G", "Tech"],
    },
    {
      id: 19,
      title: "The Future of Remote Work",
      content: "## Work from Anywhere. Insights into the evolving landscape of remote work and digital nomadism...",
      date: "August 18, 2023",
      image: Image,
      tags: ["Remote Work", "Business"],
    },
    {
      id: 20,
      title: "AI Ethics and Responsibility",
      content: "## Navigating Ethical Dilemmas. Discussing the importance of ethical considerations in AI development...",
      date: "August 19, 2023",
      image: Image,
      tags: ["AI", "Ethics"],
    },
];

export default blogPostData;
